// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJjgVAeya4m-nGFXp00EPBjklN4ndJ7A',
    appId: '1:495333670318:web:75af94362010d0b4b79c3f',
    messagingSenderId: '495333670318',
    projectId: 'taskmate-2603f',
    authDomain: 'taskmate-2603f.firebaseapp.com',
    storageBucket: 'taskmate-2603f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt6eTBVp3wDmG8MRR-uQFfK2cgqiADnvM',
    appId: '1:495333670318:android:ddc1421abc43240eb79c3f',
    messagingSenderId: '495333670318',
    projectId: 'taskmate-2603f',
    storageBucket: 'taskmate-2603f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18EwhcWbd_wXhSQUkMBj7OTEz0CY7rz8',
    appId: '1:495333670318:ios:3ee11bd40a9b4875b79c3f',
    messagingSenderId: '495333670318',
    projectId: 'taskmate-2603f',
    storageBucket: 'taskmate-2603f.firebasestorage.app',
    iosBundleId: 'com.example.skilltrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA18EwhcWbd_wXhSQUkMBj7OTEz0CY7rz8',
    appId: '1:495333670318:ios:3ee11bd40a9b4875b79c3f',
    messagingSenderId: '495333670318',
    projectId: 'taskmate-2603f',
    storageBucket: 'taskmate-2603f.firebasestorage.app',
    iosBundleId: 'com.example.skilltrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABJjgVAeya4m-nGFXp00EPBjklN4ndJ7A',
    appId: '1:495333670318:web:dd95e63d52e74c13b79c3f',
    messagingSenderId: '495333670318',
    projectId: 'taskmate-2603f',
    authDomain: 'taskmate-2603f.firebaseapp.com',
    storageBucket: 'taskmate-2603f.firebasestorage.app',
  );
}
